name: LUFT Auto Scan

on:
  push:
    paths:
      - 'data/**'
      - 'luft_auto_scan.py'

jobs:
  auto-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install numpy scipy matplotlib
      - name: Run LUFT Auto Scan
        run: python luft_auto_scan.py
      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add LUFT_Findings.md LUFT_Findings.csv
          git commit -m "Update LUFT anomaly scan results [auto]" || echo "No changes to commit"
          git push
